{
 "title": "Combined Dashboard",
 "panels": [
  { "title": "App metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frontend Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frontend_error_count or vector(0)"
    }
   ]
  },
  {
   "title": "Numbers Generated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "generator_total_numbers_generated"
    }
   ]
  },
  {
   "title": "Comparisons",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comparator_total_attempts{compare=\"-1\"}",
     "legendFormat": "Less"
    },
    {
     "expr": "comparator_total_attempts{compare=\"1\"}",
     "legendFormat": "Greater"
    }
   ]
  },
  {
   "title": "Generated numbers",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "generator_numbers_generated_bucket * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Guesses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(comparator_total_success)" }
   ]
  },
  {
   "title": "Generated numbers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "targets": [
    { "expr": "generator_generated_numbers", "legendFormat": "{{label_name}}" }
   ]
  },
  { "title": "Requests Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Frontend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by() (rate(frontend_request_processing_time_milliseconds_sum{view_name=\"begin\"}[1m]))",
     "legendFormat": "get/begin"
    },
    {
     "expr": "avg by() (rate(frontend_request_processing_time_milliseconds_sum{view_name=\"guess_number\"}[1m]))",
     "legendFormat": "get/guess_number"
    }
   ]
  },
  {
   "title": "Comparator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "avg(rate(comparator_request_duration_ms[1m]))",
     "legendFormat": "Get"
    }
   ]
  },
  {
   "title": "Generator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "avg(rate(generator_request_duration_ms[1m]))",
     "legendFormat": "Get"
    }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "avg(rate(leaderboard_request_duration_ms[1m]))",
     "legendFormat": "Get"
    }
   ]
  },
  { "title": "Number of requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Frontend",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(frontend_request_count_total{view_name=\"begin\"})",
     "legendFormat": "get/begin"
    },
    {
     "expr": "sum(frontend_request_count_total{view_name=\"guess_number\"})",
     "legendFormat": "get/guess_number"
    }
   ]
  },
  {
   "title": "Comparator",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "comparator_total_requests" }
   ]
  },
  {
   "title": "Generator",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "generator_total_requests" }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(leaderboard_request_count)", "legendFormat": "get" },
    {
     "expr": "sum(leaderboard_post_score_count)",
     "legendFormat": "post"
    }
   ]
  }
 ]
}