services:
  generator:
    build: ./generator
    restart: always
    volumes:
      - ./generator:/app
    environment:
      - REDIS_URL=redis://redis-leader:6379
      - REDIS_FOLLOWER=redis://redis-leader:6379
      - PORT=80
    depends_on:
      redis-leader:
        condition: service_healthy

  comparator:
    build: ./comparator
    restart: always
    volumes:
      - ./comparator:/app
    environment:
      - REDIS_URL=redis://redis-leader:6379
      - REDIS_FOLLOWER=redis://redis-leader:6379
      - LEADERBOARD_URL=http://leaderboard:80
      - PORT=80
    depends_on:
      redis-leader:
        condition: service_healthy

  leaderboard:
    build: ./leaderboard
    restart: always
    environment:
      - REDIS_URL=redis://redis-leader:6379
      - REDIS_FOLLOWER=redis://redis-leader:6379
      - PORT=80
    depends_on:
      redis-leader:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    volumes:
      - ./frontend:/app
    environment:
      - GENERATOR_HOST=http://generator:80
      - COMPARATOR_HOST=http://comparator:80
      - LEADERBOARD_HOST=http://leaderboard:80
      - PORT=80
    depends_on:
      redis-leader:
        condition: service_healthy

  redis-leader:
    image: redis:7.4.1
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 15