services:
  generator:
    build: ./generator
    restart: always
    volumes:
      - ./generator:/app
    environment:
      - REDIS_URL=redis://redis-leader:6379
      - REDIS_FOLLOWER=redis://redis-follower:6379
      - PORT=80

  comparator:
    build: ./comparator
    restart: always
    volumes:
      - ./comparator:/app
    environment:
      - REDIS_URL=redis://redis-leader:6379
      - REDIS_FOLLOWER=redis://redis-follower:6379
      - LEADERBOARD_URL=http://leaderboard:80
      - PORT=80

  leaderboard:
    build: ./leaderboard
    restart: always
    environment:
      - REDIS_URL=redis://redis-leader:6379
      - REDIS_FOLLOWER=redis://redis-follower:6379
      - PORT=80

  frontend:
      build: ./frontend
      ports:
        - '8080:80'
      volumes:
        - ./frontend:/app
      environment:
        - GENERATOR_HOST=http://generator:80
        - COMPARATOR_HOST=http://comparator:80
        - LEADERBOARD_HOST=http://leaderboard:80
        - PORT=80

  redis-leader:
    image: docker.io/redis:6.0.5
    restart: always 
    volumes: 
      - redis:/data

  redis-follower:
    image: gcr.io/google_samples/gb-redis-follower:v2
    restart: always 
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local