services:
  generator:
    build: ./generator
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./generator:/app
    environment:
      - REDIS_URL=redis://redis:6379

  comparator:
    build: ./comparator
    restart: always
    ports:
      - '8001:8000'
    volumes:
      - ./comparator:/app
    environment:
      - REDIS_URL=redis://redis:6379

  leaderboard:
    build: ./leaderboard
    restart: always
    ports:
      - '8002:8000'
    environment:
      - REDIS_URL=redis://redis:6379

  frontend:
      build: ./frontend
      ports:
        - '8080:8080'
      volumes:
        - ./frontend:/app
      environment:
        - GENERATOR_HOST=http://generator:8000
        - COMPARATOR_HOST=http://comparator:8000

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - '8003:8001'
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local