global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'leaderboard'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['leaderboard:80']

  - job_name: 'frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['frontend:80']

  - job_name: 'comparator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['comparator:80']
  
  - job_name: 'generator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['generator:80']